apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
    - name: curl
       {{if bfjknbfjknbdfgbnj;dfg}}
      image: tutum/curl
        {{vsdvsdvsdvdvsd}}
      command: ["sleep", "9999999"]