apiVersion: batch/v1
kind: Deployment
metadata:
  name: batch
  labels:
    type: cuatc
spec:
  completions: 5
  parallelism: 5
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job
          args: 222