@Library('yaml') _
import main.groovy.org.example.classes.YamlFile

pipeline {
    agent any

    options {
        timestamps ()
    }

    parameters {
        string(name: 'ARCHIVE_1', description: 'the name of the first archive')
        string(name: 'ARCHIVE_2', description: 'the name of the second archive')
    }

    stages{
        stage('second'){
            steps {
                script {

                    HelloWorld(this)
                }
            }
        }
    }
}